# Literals
PYDOCURL = 'https://docs.python.org/3/'
OBJ3_FOLDER_COUNT = 266
OBJ4_SIZE = 10655

# Data File Paths
DATAPATH = 'PyMaker/datas/'
OBJ3_DATAPATH = DATAPATH + 'object3/'
OBJ4_DATAPATH = DATAPATH + 'object4/1st/'
OBJ4_VECREP_PATH = DATAPATH + 'object4_subword_vecrep/'
PYTHONDOCTONUM = DATAPATH + 'pythonDocToNumber.txt'
NUMTOPYTHONDOC = DATAPATH + 'numberToPythonDoc.txt'
GOOGLE_W2V_PATH = DATAPATH + 'GoogleNews/GoogleNews-vectors-negative300.bin'

# obj3_read.py specific
OBJ3_READ_SET_GLOBAL_VARIABLES = True
OBJ3_READ_SET_GLOBAL_VARIABLES_PRINT_LOG = True
OBJ3_READ_ANSWERURL_DELIM = 'Answer URL'
OBJ3_READ_NATTEXT_DELIM = 'Natural Text'

# google_w2v.py specific
GOOGLE_W2V_SET_GLOBAL_VARIABLES = True
GOOGLE_W2V_SET_GLOBAL_VARIABLES_PRINT_LOG = True
GOOGLE_W2V_NEAR_ZERO = 1e-8
GOOGLE_W2V_SUBWORD_LENGTH_LOW = 2
GOOGLE_W2V_SUBWORD_LENGTH_HIGH = 6


N_FOR_TOP_N_VALUES = 5
N_FOR_TESTCASE_NUM = 20

OBJ4_VECREP_CALC_TEST = False

SERVICE_TOP_N = 0
SERVICE_UPPERDOC = True
