OBJ4_PATH = 'PyMaker/datas/object4/1st/'
OBJ4_VECREP_PATH = 'PyMaker/datas/object4_wv_rep/'
OBJ4_SIZE = 10655

N_FOR_TOP_N_VALUES = 5
N_FOR_TESTCASE_NUM = 20

OBJ4_VECREP_CALC_TEST = False

SERVICE_TOP_N = 5
SERVICE_UPPERDOC = True
